In [2]:
import pandas as pd
from sqlalchemy import create_engine

path = '/home/emmanuel/Desktop/descarga_db/raw_data_project_m1.db'
engine = create_engine(f'sqlite:///{path}')

raw_df = pd.read_sql_query("SELECT * FROM sqlite_master WHERE type='table'", engine)

raw_df

,type,name,tbl_name,rootpage,sql
0,table,personal_info,personal_info,2,CREATE TABLE personal_info (\n\tuuid TEXT NOT ...
1,table,country_info,country_info,401,CREATE TABLE country_info (\n\tuuid TEXT NOT N...
2,table,career_info,career_info,762,CREATE TABLE career_info (\n\tuuid TEXT NOT NU...
3,table,poll_info,poll_info,1168,CREATE TABLE poll_info (\n\tuuid TEXT NOT NULL...

In [12]:
df = pd.read_sql("""SELECT * 
                 FROM personal_info 
                 JOIN poll_info 
                 ON poll_info.uuid = personal_info.uuid 
                 GROUP BY personal_info.uuid;""",engine)
df

,uuid,age,gender,dem_has_children,age_group,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,0001afe0-da16-0133-9d54-0a81e8b09a82,31 years old,male,nO,26_39,0001afe0-da16-0133-9d54-0a81e8b09a82,I know something about it,I would probably vote against it,‰Û_ do more volunteering work,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
1,00073240-d995-0133-f7e1-0a81e8b09a82,35 years old,male,NO,26_39,00073240-d995-0133-f7e1-0a81e8b09a82,I have never heard of it,I would not vote,None of the above,None of the above,None of the above
2,0007b2d0-daf3-0133-c5f0-0a81e8b09a82,1988,FeMale,YES,26_39,0007b2d0-daf3-0133-c5f0-0a81e8b09a82,I have heard just a little about it,I would vote against it,‰Û_ work less,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...
3,00199e00-d8c3-0133-c6b2-0a81e8b09a82,2000,Male,NO,juvenile,00199e00-d8c3-0133-c6b2-0a81e8b09a82,I have never heard of it,I would not vote,None of the above,None of the above,None of the above
4,0028cc20-dcc4-0133-f408-0a81e8b09a82,1988,female,YES,26_39,0028cc20-dcc4-0133-f408-0a81e8b09a82,I know something about it,I would probably vote for it,A basic income would not affect my work choices,None of the above,It is against the principle of linking merit a...
...,...,...,...,...,...,...,...,...,...,...,...
9644,ffe6bd40-d98a-0133-a373-0a81e8b09a82,53 years old,male,YES,40_65,ffe6bd40-d98a-0133-a373-0a81e8b09a82,I know something about it,I would probably vote against it,‰Û_ work less,It reduces anxiety about financing basic needs,Only the people who need it most should get so...
9645,fff34480-db17-0133-381a-0a81e8b09a82,45 years old,male,nO,40_65,fff34480-db17-0133-381a-0a81e8b09a82,I know something about it,I would vote for it,‰Û_ work as a freelancer,It creates more equality of opportunity,Foreigners might come to my country and take a...
9646,fffa2a60-dc71-0133-8480-0a81e8b09a82,53 years old,female,yES,40_65,fffa2a60-dc71-0133-8480-0a81e8b09a82,I have heard just a little about it,I would vote against it,None of the above,None of the above,Only the people who need it most should get so...
9647,fffcd3a0-d975-0133-b045-0a81e8b09a82,38 years old,Male,NO,26_39,fffcd3a0-d975-0133-b045-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It creates more equality of opportunity | It r...,It might encourage people to stop working
9648,ffffd3f0-da39-0133-da0f-0a81e8b09a82,44 years old,Male,YES,40_65,ffffd3f0-da39-0133-da0f-0a81e8b09a82,I know something about it,I would vote against it,A basic income would not affect my work choices,None of the above,It increases dependence on the state | It is i...

In [14]:
personal_info = pd.read_sql("SELECT * FROM personal_info",engine)
personal_info

,uuid,age,gender,dem_has_children,age_group
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65
...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65

In [15]:
country = pd.read_sql("SELECT * FROM country_info",engine)
country

                                      uuid country_code        rural
0     f6e7ee00-deac-0133-4de8-0a81e8b09a82           AT  countryside
1     54f0f1c0-dda1-0133-a559-0a81e8b09a82           AT        urban
2     83127080-da3d-0133-c74f-0a81e8b09a82           AT         city
3     15626d40-db13-0133-ea5c-0a81e8b09a82           AT      Country
4     24954a70-db98-0133-4a64-0a81e8b09a82           AT         city
...                                    ...          ...          ...
9644  7d1ac020-dcb4-0133-817a-0a81e8b09a82           SK        urban
9645  39f989f0-db52-0133-8482-0a81e8b09a82           SK        urban
9646  70ce4a90-d965-0133-f5e4-0a81e8b09a82           SK    Non-Rural
9647  2896e440-db3c-0133-5b67-0a81e8b09a82           SK         city
9648  06217ba0-dd56-0133-edda-0a81e8b09a82           SK         city

[9649 rows x 3 columns]

In [ ]:
http://api.dataatwork.org/v1/spec/skills-api.json

In [16]:
career = pd.read_sql("SELECT * FROM career_info",engine)
career

,uuid,dem_education_level,dem_full_time_job,normalized_job_code
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0
2,83127080-da3d-0133-c74f-0a81e8b09a82,None,no,None
3,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c
4,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f
...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,high,yes,847165cfda6b1dc82ae22b967da8af2f
9645,39f989f0-db52-0133-8482-0a81e8b09a82,high,yes,a4d5b8b38f9513825d0d94a981ebe962
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,low,no,None
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,low,yes,775190277a849cba701b306a7b374c0a
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,high,yes,8a7a3f1bce0958ae9f090683e5a925b7

In [17]:
poll_info = pd.read_sql("SELECT * FROM poll_info",engine)
poll_info

,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [22]:
df = pd.concat([personal_info,country,career,poll_info],axis=1,sort=True)
df

,uuid,age,gender,dem_has_children,age_group,uuid,country_code,rural,uuid,dem_education_level,dem_full_time_job,normalized_job_code,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,f6e7ee00-deac-0133-4de8-0a81e8b09a82,AT,countryside,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,54f0f1c0-dda1-0133-a559-0a81e8b09a82,AT,urban,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,83127080-da3d-0133-c74f-0a81e8b09a82,AT,city,83127080-da3d-0133-c74f-0a81e8b09a82,None,no,None,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,15626d40-db13-0133-ea5c-0a81e8b09a82,AT,Country,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,24954a70-db98-0133-4a64-0a81e8b09a82,AT,city,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,7d1ac020-dcb4-0133-817a-0a81e8b09a82,SK,urban,7d1ac020-dcb4-0133-817a-0a81e8b09a82,high,yes,847165cfda6b1dc82ae22b967da8af2f,7d1ac020-dcb4-0133-817a-0a81e8b09a82,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,39f989f0-db52-0133-8482-0a81e8b09a82,SK,urban,39f989f0-db52-0133-8482-0a81e8b09a82,high,yes,a4d5b8b38f9513825d0d94a981ebe962,39f989f0-db52-0133-8482-0a81e8b09a82,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,70ce4a90-d965-0133-f5e4-0a81e8b09a82,SK,Non-Rural,70ce4a90-d965-0133-f5e4-0a81e8b09a82,low,no,None,70ce4a90-d965-0133-f5e4-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,2896e440-db3c-0133-5b67-0a81e8b09a82,SK,city,2896e440-db3c-0133-5b67-0a81e8b09a82,low,yes,775190277a849cba701b306a7b374c0a,2896e440-db3c-0133-5b67-0a81e8b09a82,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,06217ba0-dd56-0133-edda-0a81e8b09a82,SK,city,06217ba0-dd56-0133-edda-0a81e8b09a82,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,06217ba0-dd56-0133-edda-0a81e8b09a82,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [24]:
pd

ValueError: Grouper for 'uuid' not 1-dimensional