In [1]:
import pandas as pd
from sqlalchemy import create_engine


path = '/home/emmanuel/Desktop/descarga_db/raw_data_project_m1.db'
engine = create_engine(f'sqlite:///{path}')

raw_df = pd.read_sql_query("SELECT * FROM sqlite_master WHERE type='table'", engine)

raw_df

,type,name,tbl_name,rootpage,sql
0,table,personal_info,personal_info,2,CREATE TABLE personal_info (\n\tuuid TEXT NOT ...
1,table,country_info,country_info,401,CREATE TABLE country_info (\n\tuuid TEXT NOT N...
2,table,career_info,career_info,762,CREATE TABLE career_info (\n\tuuid TEXT NOT NU...
3,table,poll_info,poll_info,1168,CREATE TABLE poll_info (\n\tuuid TEXT NOT NULL...

In [2]:
df_raw = pd.read_sql("""SELECT personal_info.uuid,
personal_info.age,
personal_info.dem_has_children,
personal_info.gender,
career_info.dem_education_level,
career_info.dem_full_time_job,
career_info.normalized_job_code,
country_info.country_code,
poll_info.question_bbi_2016wave4_basicincome_argumentsagainst,
poll_info.question_bbi_2016wave4_basicincome_argumentsfor,
poll_info.question_bbi_2016wave4_basicincome_awareness 
FROM personal_info
JOIN career_info 
ON career_info.uuid = personal_info.uuid
JOIN country_info 
ON country_info.uuid = personal_info.uuid
JOIN poll_info 
ON poll_info.uuid = country_info.uuid 
GROUP BY career_info.uuid;""",engine)
df_raw

,uuid,age,dem_has_children,gender,dem_education_level,dem_full_time_job,normalized_job_code,country_code,question_bbi_2016wave4_basicincome_argumentsagainst,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_awareness
0,0001afe0-da16-0133-9d54-0a81e8b09a82,31 years old,nO,male,high,yes,7932d4705d002b47789c11edfaed685e,NL,Foreigners might come to my country and take a...,It reduces bureaucracy and administrative expe...,I know something about it
1,00073240-d995-0133-f7e1-0a81e8b09a82,35 years old,NO,male,medium,no,None,HR,None of the above,None of the above,I have never heard of it
2,0007b2d0-daf3-0133-c5f0-0a81e8b09a82,1988,YES,FeMale,medium,yes,e7b3e1c6a32c7247cd4857e4c3574165,DE,It might encourage people to stop working | It...,It reduces bureaucracy and administrative expe...,I have heard just a little about it
3,00199e00-d8c3-0133-c6b2-0a81e8b09a82,2000,NO,Male,low,no,None,IT,None of the above,None of the above,I have never heard of it
4,0028cc20-dcc4-0133-f408-0a81e8b09a82,1988,YES,female,high,no,None,FR,It is against the principle of linking merit a...,None of the above,I know something about it
...,...,...,...,...,...,...,...,...,...,...,...
9644,ffe6bd40-d98a-0133-a373-0a81e8b09a82,53 years old,YES,male,medium,yes,ac47656fd51c2cd8037057262c910dc4,FR,Only the people who need it most should get so...,It reduces anxiety about financing basic needs,I know something about it
9645,fff34480-db17-0133-381a-0a81e8b09a82,45 years old,nO,male,high,yes,ac47656fd51c2cd8037057262c910dc4,DE,Foreigners might come to my country and take a...,It creates more equality of opportunity,I know something about it
9646,fffa2a60-dc71-0133-8480-0a81e8b09a82,53 years old,yES,female,low,no,None,ES,Only the people who need it most should get so...,None of the above,I have heard just a little about it
9647,fffcd3a0-d975-0133-b045-0a81e8b09a82,38 years old,NO,Male,high,no,None,LT,It might encourage people to stop working,It creates more equality of opportunity | It r...,I understand it fully
9648,ffffd3f0-da39-0133-da0f-0a81e8b09a82,44 years old,YES,Male,high,yes,d06dfb43c95b585a89ae556c9221b573,FR,It increases dependence on the state | It is i...,None of the above,I know something about it

In [ ]:
#personal_info = pd.read_sql("SELECT * FROM personal_info",engine)
#personal_info
#country = pd.read_sql("SELECT * FROM country_info",engine)
#country
#career = pd.read_sql("SELECT * FROM career_info",engine)
#career
#poll_info = pd.read_sql("SELECT * FROM poll_info",engine)
#poll_info

In [3]:
import requests

In [4]:
req = requests.get('http://api.dataatwork.org/v1/jobs?')
r_j_son = req.json()
r_j_son = pd.DataFrame(r_j_son)
#r_j_son.head()

In [15]:
#dataframe just with jobs and normalized names
jobs_df = r_j_son.drop(columns=['parent_uuid','links'])
jobs_df = jobs_df.rename(columns={'uuid':'normalized_job_code'})
jobs_df.to_csv('jobs_df.csv',index=False)

In [24]:
#merge both df

,uuid,age,dem_has_children,gender,dem_education_level,dem_full_time_job,normalized_job_code,country_code,question_bbi_2016wave4_basicincome_argumentsagainst,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_awareness,title,normalized_job_title
0,00073240-d995-0133-f7e1-0a81e8b09a82,35 years old,NO,male,medium,no,None,HR,None of the above,None of the above,I have never heard of it,NaN,NaN
1,00199e00-d8c3-0133-c6b2-0a81e8b09a82,2000,NO,Male,low,no,None,IT,None of the above,None of the above,I have never heard of it,NaN,NaN
2,0028cc20-dcc4-0133-f408-0a81e8b09a82,1988,YES,female,high,no,None,FR,It is against the principle of linking merit a...,None of the above,I know something about it,NaN,NaN
3,003409e0-db2a-0133-cbe7-0a81e8b09a82,46 years old,yES,FeMale,medium,no,None,NL,Foreigners might come to my country and take a...,It increases appreciation for household work a...,I have never heard of it,NaN,NaN
4,00415000-dbdb-0133-31c4-0a81e8b09a82,43 years old,yES,female,medium,no,None,GB,None of the above,None of the above,I have never heard of it,NaN,NaN

In [6]:
#country codes through webscrapping

url = 'https://countrycode.org/' 
raw_codes = pd.read_html(url,header=0)[0]

#only keeping columns that are needed
country_codes = raw_codes.drop(columns=['COUNTRY CODE','POPULATION','AREA KM2','GDP $USD'])

In [14]:
country_codes.to_csv('country_codes.csv',index=False)